apiVersion: apps/v1
kind: Deployment
metadata:
  name: workon-deployment
spec:
  selector:
    matchLabels:
      app: workon
  replicas: 2
  template:
    metadata:
      labels:
        app: workon
    spec:
      containers:
      - name: workon
        image: rfahham/workon:2.0.0
        ports:
        - containerPort: 80

# kubectl port-forward deployment.apps/workon-deployment 8080:80

# kubectl delete -f workon/deployment.yaml